package com.achcar_solutions.easycomm_core.entities.opportunity;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "opportunities")
@Schema(description = "Represents a complementary hour opportunity in the system.")
public class Opportunity {
    @MongoId(FieldType.OBJECT_ID)
    @Schema(description = "Unique ID of the opportunity generated by MongoDB.", example = "60d5f1b3e6b3f1a2b3c4d5e7")
    private String id;

    @Schema(description = "Title of the opportunity.", example = "Monitoria de Cálculo I")
    private String title;

    @Schema(description = "Detailed description of the opportunity.", example = "Vaga para monitor da disciplina de Cálculo I, auxiliando alunos com dúvidas e na correção de listas.")
    private String description;

    @Schema(description = "Course associated with the opportunity.", example = "Ciência da Computação")
    private String course;

    @Schema(description = "Number of complementary hours awarded.", example = "60")
    private Integer hours;

    @Schema(description = "Current status of the opportunity.")
    private OpportunityStatus status;

    @Schema(description = "Identifier of the user who created the opportunity.", example = "admin@email.com")
    private String createdBy;

    @Schema(description = "List of user IDs that applied for the opportunity.", example = "[\"user1@email.com\", \"user2@email.com\"]")
    private List<String> applicants;
}
